services:
  nginx:
    image: nginx:latest
    container_name: music-library-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app
  app:
    image: yaysfan/music-library:latest
    container_name: music-library-app
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - /home/ubuntu/songs:/data/songs
      - /home/ubuntu/cookies.txt:/data/cookies.txt
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  db:
    image: postgres:15-alpine
    container_name: music-library-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=music
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: music-library-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: