# 모든 환경에 적용되는 공통 설정 + 기본 프로필 지정
spring:
  profiles:
    # 별도 설정이 없으면 항상 'local' 프로필을 활성화
    active: local
    include: oauth
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs
org:
  jobrunr:
    background-job-server:
      enabled: false
    dashboard:
      enabled: false
config:
  jobs:
    clear-songs:
      cron: "*/15 * * * *"
  jwt:
    expiration: 86400 # in seconds
logging:
  level:
    org.hibernate.SQL: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always