# 'test' 프로필에서만 적용될 설정

spring:
  cloud:
    aws:
      secretsmanager:
        enabled: false
      stack:
        auto: false
      region:
        auto: false

config:
  yt-dlp:
    path: "dummy"
    ffmpeg-directory: "dummy"
    cookies-file: "dummy"