#  운영 환경(prod profile)에서만 적용되는 설정
spring:
  config:
    import: "aws-secretsmanager:music"
  datasource:
    url: jdbc:postgresql://db:5432/music
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: music-library-redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
config:
  file:
    base-path: "/data/songs"
  yt-dlp:
    ffmpeg-directory: "/usr/bin"
    path: "/usr/local/bin/yt-dlp"
    cookies-file: "/data/cookies.txt"
aws:
  region:
    static: ap-northeast-2