#  로컬 환경(local profile)에서만 적용되는 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music
    username: yaysfan
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
config:
  file:
    base-path: "./songs"
  yt-dlp:
    ffmpeg-directory: "C:\\ffmpeg-8.0-essentials_build\\bin"
    path: "C:\\ffmpeg-8.0-essentials_build\\bin\\yt-dlp.exe"
    cookies-file: "C:\\ffmpeg-8.0-essentials_build\\bin\\.cookies.txt"
  jwt:
    private:
      key: classpath:app.key
    public:
      key: classpath:app.pub
