name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: music
          POSTGRES_USER: yaysfan
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >- 
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Grant execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Create RSA key files
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_KEY }}" > src/main/resources/app.key
          echo "${{ secrets.APP_PUB }}" > src/main/resources/app.pub

      - name: Build with Maven
        run: ./mvnw test
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/music
          SPRING_DATASOURCE_USERNAME: yaysfan
          SPRING_DATASOURCE_PASSWORD: 1234
          SPRING_DATA_REDIS_HOST: localhost
          SPRING_DATA_REDIS_PORT: 6379