name: Secret Access Test

on:
  push:
    branches: [ "main" ]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets to log
        run: |
          echo "Attempting to print APP_KEY secret:"
          echo "${{ secrets.APP_KEY }}"
          
          echo "Attempting to print APP_PUB secret:"
          echo "${{ secrets.APP_PUB }}"